name: Create Singularity Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Singularity
        run: |
          VERSION=3.7.1  # Replace with desired Singularity version
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz
          tar xvf singularity-${VERSION}.tar.gz
          cd singularity-${VERSION}
          ./mconfig
          make -C builddir
          sudo make -C builddir install
          cd ..
          rm -rf singularity-${VERSION} singularity-${VERSION}.tar.gz
      
      - name: Build Singularity image
        run: singularity build gSmVs.sif Singularity
          
      - name: Save Singularity image to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gSmVs.sif
          path: ./gSmVs.sif
