name: Create Singularity Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v2
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          # Add the following lines to use Node.js 16
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install Singularity
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -fsSL https://download.apptainer.io/linux/install.sh | sudo bash
      
      - name: Build Singularity image
        run: singularity build gSmVs.sif Singularity
          
      - name: Save Singularity image to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gSmVs.sif
          path: ./gSmVs.sif
